export {
    faSun,
    faMoon,
    faBell,
    faCircleQuestion,
    faCircleUser,
    faMagnifyingGlass,
    faUsers,
    faUser,
    faMedal,
    faTachographDigital,
    faBriefcase,
    faCreditCard,
    faChartSimple,
} from '@fortawesome/free-solid-svg-icons';